### PR TITLE
Splitting code in modules

### PR DESCRIPTION
**Pull request by hrshdhgd**
- `lib.rs`: Main library crate
 - `file_io.rs`: Read files and form dicts from csv.
 - `similarity.rs`: Jaccard (for now) and the others like IC, Resnik etc will reside in this module
 - `structs.rs`: All struct and strict implementations/functions/methods in here.

### CODE REVIEW

**Comment by caufieldjh** [comment]
I know this is in-progress so apologies if you're already on this - I get a compilation error of ```error: there is no argument named `tsps_information`stsim``` in lib.rs

**Comment by caufieldjh** [comment]
I think that's some weirdness in the log output, since normally an error or warning looks like this, with the module name at the end of the line:
```
warning: variable does not need to be mutable/59: rustsim
  --> src/lib.rs:26:9
```

**Comment by hrshdhgd** [comment]
Try pulling and run `maturin develop` and the whole python spiel. It should work. I think all the errors was because of the Vector I introduced in the code. I took it off since it doesn't serve our purpose once we figure out `yield`.

**Comment by caufieldjh** [comment]
Weird, now I'm back to getting that initial compilation error:
```
~/rustsim$ maturin develop
🔗 Found pyo3 bindings
🐍 Found CPython 3.8 at /home/harry/rustsim/rustsim_env/bin/python
   Compiling rustsim v0.1.0 (/home/harry/rustsim)
error: there is no argument named `tsps_information`stsim
  --> src/lib.rs:46:19
   |
46 |         println!("{tsps_information:#?}")
   |                   ^^^^^^^^^^^^^^^^^^^^^
   |
   = help: if you intended to capture `tsps_information` from the surrounding scope, add `#![feature(format_args_capture)]` to the crate attributes


error: aborting due to previous error==> ] 58/59: rustsim


error: could not compile `rustsim` due to 2 previous errors
💥 maturin failed
  Caused by: Failed to build a native library through cargo
  Caused by: Cargo build finished with "exit status: 101": `"cargo" "rustc" "--manifest-path" "/home/harry/rustsim/Cargo.toml" "--message-format" "json" "--lib"`
```

**Comment by caufieldjh** [comment]
Adding `#![feature(format_args_capture)]` to the top of `lib.rs` fixes that error. I'll push the fix here, but feel free to revert if it breaks on your end, of course

**Comment by hrshdhgd** [comment]
```
`#![feature]` may not be used on the stable release channel
the feature `format_args_capture` has been stable since 1.58.0 and no longer requires an attribute to enable

`#![feature]` may not be used on the stable release channel
the feature `format_args_capture` has been stable since 1.58.0 and no longer requires an attribute to enable
```

Is your rust version the latest one?

**Comment by caufieldjh** [comment]
Aha! I'm on the same version - but on nightly, not stable.

**Comment by caufieldjh** [comment]
For future reference, this is fixed by running `rustup default stable`, and the required toolchain for this project can be specified in a config file named `rust-toolchain.toml` ([like this](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)) if it becomes necessary.

**Pull request merged**
